language: python
cache: pip

matrix:
  include:
    - language: python
      python: "3.5"
      env: TOXENV=py35-ansible24

    - language: python
      python: "3.6"
      env: TOXENV=py36-ansible24

    - language: python
      python: "2.7"
      env: TOXENV=py27-ansible24

    - language: python
      python: "3.5"
      env: TOXENV=py35-latest

    - language: python
      python: "3.6"
      env: TOXENV=py36-latest

    - language: python
      python: "2.7"
      env: TOXENV=py27-latest

    - language: python
      python: "2.7"
      env: TOXENV=pep8

install:
    - pip install tox
    - if [ "$TOXENV" = 'py27-latest' ]; then pip install codecov; fi
script:
    - tox -e $TOXENV
after_success:
    - if [ "$TOXENV" = 'py27-latest' ]; then codecov; fi
deploy:
    provider: pypi
    distributions: "sdist bdist_wheel"
    user: seantis
    password:
      secure: "p5EE2MePFHvfe5EWyrbO+V/a+JXjfJ3wYVQB5N+1Ap3QSmQQoworq1x+zufuI9wK0R8f1eCSnaSyWM7vw+i6aBLgilGLbjvax6PEJdSMmQ1vRC1hpEnXVcvpZc//gEdJzC5vcA9/ZqtXQXVbrLcd6eloPggKrjTstx/pmGnQcVY="
    on:
        tags: true
        condition: $TOXENV = py27-latest
